applicationName: "deployment-test"

image:
  repository: nginxdemos/hello
  tag: stable
  pullPolicy: Always

ports:
  - name: http
    port: 80
    protocol: TCP

probe:
  httpGet:
    path: /
    port: 80